export const Pairs = [
  //forex
  {
    name: "AUDUSD",
    contractSize: 100000,
    tickSize: 0.00001,
    base: "AUD",
    quote: "USD",
  },
  {
    name: "GBPUSD",
    contractSize: 100000,
    tickSize: 0.00001,
    base: "GBP",
    quote: "USD",
  },
  {
    name: "USDCAD",
    contractSize: 100000,
    tickSize: 0.001,
    base: "USD",
    quote: "CAD",
    apiName: "USD/CAD",
  },
  {
    name: "USDCHF",
    contractSize: 100000,
    tickSize: 0.00001,
    base: "USD",
    quote: "CHF",
  },
  {
    name: "USDJPY",
    contractSize: 100000,
    tickSize: 0.001,
    base: "USD",
    quote: "JPY",
    apiName: "USD/JPY",
  },
  {
    name: "NZDUSD",
    contractSize: 100000,
    tickSize: 0.00001,
    base: "NZD",
    quote: "USD",
  },
  {
    name: "AUDNZD",
    contractSize: 100000,
    tickSize: 0.001,
    base: "AUD",
    quote: "NZD",
    apiName: "USD/NZD",
  },
  {
    name: "AUDCAD",
    contractSize: 100000,
    tickSize: 0.00001,
    base: "AUD",
    quote: "CAD",
    apiName: "USD/CAD",
  },
  {
    name: "AUDCHF",
    contractSize: 100000,
    tickSize: 0.00001,
    base: "AUD",
    quote: "CHF",
    apiName: "USD/CHF",
  },
  {
    name: "AUDJPY",
    contractSize: 100000,
    tickSize: 0.001,
    base: "AUD",
    quote: "JPY",
    apiName: "USD/JPY",
  },
  {
    name: "CADCHF",
    contractSize: 100000,
    tickSize: 0.00001,
    base: "CAD",
    quote: "CHF",
    apiName: "USD/CHF",
  },
  {
    name: "CADJPY",
    contractSize: 100000,
    tickSize: 0.001,
    base: "CAD",
    quote: "JPY",
    apiName: "USD/JPY",
  },
  {
    name: "CHFJPY",
    contractSize: 100000,
    tickSize: 0.001,
    base: "CHF",
    quote: "JPY",
    apiName: "USD/CHF",
  },
  {
    name: "EURAUD",
    contractSize: 100000,
    tickSize: 0.00001,
    base: "EUR",
    quote: "AUD",
    apiName: "USD/AUD",
  },

  {
    name: "EURUSD",
    contractSize: 100000,
    tickSize: 0.00001,
    base: "EUR",
    quote: "USD",
  },
  {
    name: "EURNZD",
    contractSize: 100000,
    tickSize: 0.00001,
    base: "EUR",
    quote: "NZD",
    apiName: "NZD/USD",
  },

  {
    name: "GBPCHF",
    contractSize: 100000,
    tickSize: 0.00001,
    base: "GBP",
    quote: "CHF",
    apiName: "USD/CHF",
  },
  {
    name: "GBPJPY",
    contractSize: 100000,
    tickSize: 0.001,
    base: "GBP",
    quote: "JPY",
    apiName: "USD/JPY",
  },
  {
    name: "GBPAUD",
    contractSize: 100000,
    tickSize: 0.00001,
    base: "GBP",
    quote: "AUD",
    apiName: "USD/AUD",
  },
  {
    name: "EURGBP",
    contractSize: 100000,
    tickSize: 0.00001,
    base: "EUR",
    quote: "GBP",
    apiName: "USD/GBP",
  },
  {
    name: "EURJPY",
    contractSize: 100000,
    tickSize: 0.01,
    base: "EUR",
    quote: "JPY",
    apiName: "USD/JPY",
  },
  {
    name: "EURCHF",
    contractSize: 100000,
    tickSize: 0.00001,
    base: "EUR",
    quote: "CHF",
    apiName: "CHF/USD",
  },
  {
    name: "NZDJPY",
    contractSize: 100000,
    tickSize: 0.001,
    base: "NZD",
    quote: "JPY",
    apiName: "USD/JPY",
  },
  {
    name: "EURCAD",
    contractSize: 100000,
    tickSize: 0.00001,
    base: "EUR",
    quote: "CAD",
    apiName: "USD/CAD",
  },

  //metals
  {
    name: "XAUUSD",
    contractSize: 100,
    tickSize: 0.01,
    base: "XAU",
    quote: "USD",
  },
  {
    name: "XPDUSD",
    contractSize: 100,
    tickSize: 0.01,
    base: "XPD",
    quote: "USD",
  },
  {
    name: "XPTUSD",
    contractSize: 100,
    tickSize: 0.01,
    base: "XPT",
    quote: "USD",
  },
  {
    name: "XAGUSD",
    contractSize: 5000,
    tickSize: 0.001,
    base: "XAG",
    quote: "USD",
  },
  {
    name: "XAGEUR",
    contractSize: 5000,
    tickSize: 0.001,
    base: "XAG",
    quote: "EUR",
    apiName: "EUR/USD",
  },

  // commodities
  {
    name: "BRNUSD",
    contractSize: 1000,
    tickSize: 0.001,
    base: "BRN",
    quote: "USD",
  },
  {
    name: "NGCUSD",
    contractSize: 10000,
    tickSize: 0.0001,
    base: "NGC",
    quote: "USD",
  },
  {
    name: "WTIUSD",
    contractSize: 1000,
    tickSize: 0.001,
    base: "WTI",
    quote: "USD",
  },
  // index
  {
    name: "DJIUSD",
    contractSize: 10,
    tickSize: 0.1,
    base: "DJI",
    quote: "USD",
  },
  {
    name: "SPXUSD",
    contractSize: 10,
    tickSize: 0.01,
    base: "SPX",
    quote: "USD",
  },
  {
    name: "NDXUSD",
    contractSize: 10,
    tickSize: 0.1,
    base: "NDX",
    quote: "USD",
  },

  // crypto
  {
    name: "BTCUSD",
    contractSize: 1,
    tickSize: 0.01,
    base: "BTC",
    quote: "USD",
  },
];
