name: opo-ci-cd.yml

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Dependencies for Frontend
        working-directory: ./var/www/front
        run: npm install

      - name: Build Frontend
        working-directory: ./var/www/front
        run: npm run build

      - name: Install Dependencies for Backend
        working-directory: ./var/www/back/
        run: npm install

      - name: Build Backend
        working-directory: ./var/www/back/
        run: npm run build

      - name: Deploy to Server
        env:
          SERVER_PASSWORD: ${{secrets.SERVER_PASSWORD}}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          sudo apt-get install -y sshpass
          rsync -avz --delete-after -e "sshpass -p '${SERVER_PASSWORD}' ssh -o StrictHostKeyChecking=no" ./var/www/front/ ${SERVER_USER}@${SERVER_HOST}:${DEPLOY_PATH}/frontend
          rsync -avz --delete-after -e "sshpass -p '${SERVER_PASSWORD}' ssh -o StrictHostKeyChecking=no" ./var/www/back/ ${SERVER_USER}@${SERVER_HOST}:${DEPLOY_PATH}/backend
          sshpass -p "${SERVER_PASSWORD}" ssh -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_HOST} <<-EOF
            cd ${DEPLOY_PATH}/backend
            npm install --production
            pm2 restart all
          EOF
